#!/bin/bash

user=$1
pass=$2
perm=$3

echo $user
echo $pass
echo $perm

if [[$user<>"" ]]
then
sudo  mkdir -p /home/$user/ftp;
sudo chown -R $user. /home/$user/ftp;
sudo chmod -R go=$perm /home/$user/ftp;

sudo groupadd $user
sudo useradd -p -m -d /home/$user -s /bin/bash -g $user $user;
 
(echo $user; echo $pass) | passwd $user;

sudo echo 'Proverochni text' > /home/$user/ftp/proverka.txt;

if [[$perm=r]]
then
sudo chown -R $user. /home/$user;
sudo chmod -R 555 /home/$user/ftp;
else
fi
if [[$perm=rw]]
then
sudo chown -R $user. /home/$user;
sudo chmod -R 777 /home/$user/ftp;
else
fi
sudo echo $user >> /etc/vsftpd.userlist;
sudo echo $user >> /etc/vsftpd.chroot_list;

sudo systemctl restart vsftpd
else
fi
