#!/bin/bash
user=$1
pass=$2
perm=$3
echo $user
echo $pass
echo $perm
if [[ -n $user && -n $pass && "$perm" == "r" || "$perm" == "rw" ]]
then
sudo mkdir -p /home/$user/ftp
sudo echo 'Proverochni text' > /home/$user/ftp/proverka.txt
sudo echo $user >> /etc/vsftpd.userlist

(echo $pass; echo $pass; ) |  adduser $user
#(echo $user; echo $pass) | passwd $user;
else echo "Err. Value must not be empty" 
fi
if [[ "$perm" == "r" && -n $user && -n $pass]]
then
sudo chown $user /home/$user/ftp
sudo chmod 555 /home/$user/ftp

elif [[ "$perm" == "rw" && -n $user && -n $pass]]
then
sudo chown $user /home/$user/ftp
sudo chmod 777 /home/$user/ftp
fi
sudo systemctl restart vsftpd
